### ISSUE TITLE
Chart doesn't display on IOS Emulator(physical phone didn't check)

### ISSUE THREAD

**Issue by ShaggyGettu** [jja08111/time_chart#22]
Chart don't work on IOS emulator work on the example presented in README.

Error Log:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building CanvasTouchDetector(dirty, state:
_CanvasTouchDetectorState#ffa39):
Incorrect GestureDetector arguments.
Having both a pan gesture recognizer and a scale gesture recognizer is redundant; scale is a
superset of pan.
Just use the scale gesture recognizer.

The relevant error-causing widget was:
  CanvasTouchDetector
  CanvasTouchDetector:file:///Users/shaygettu/development/flutter_sdk/flutter/.pub-cache/hosted/pub.dartlang.org/time_chart-0.3.3/lib/src/chart.dart:470:28

When the exception was thrown, this was the stack:
#0      new GestureDetector.<anonymous closure> (package:flutter/src/widgets/gesture_detector.dart:245:14)
#1      new GestureDetector (package:flutter/src/widgets/gesture_detector.dart:263:9)
#2      _CanvasTouchDetectorState.build (package:touchable/src/canvas_touch_detector.dart:38:16)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4870:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4754:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735:5)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919:11)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729:5)
...     Normal element mounting (91 frames)
#100    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#101    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#102    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (7 frames)
#109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#110    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#111    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (32 frames)
#143    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#144    Element.updateChild (package:flutter/src/widgets/framework.dart:3540:18)
#145    _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:138:18)
#146    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2600:19)
#147    _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:156:12)
#148    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1997:59)
#149    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:918:15)
#150    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1997:14)
#151    RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:230:7)
#152    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:319:5)
#153    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#154    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#155    RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:829:43)
#156    RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#157    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#158    _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:504:14)
#159    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#160    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#161    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#162    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#163    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#164    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#165    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#166    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#167    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#168    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#169    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#170    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#171    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#172    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#173    RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:896:45)
#174    RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#175    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#176    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#177    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1005:7)
#178    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#179    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#180    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#181    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#182    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#183    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#184    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#185    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#186    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#187    RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:896:45)
#188    RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#189    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#190    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#191    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#192    RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:277:14)
#193    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#194    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#195    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#196    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#197    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#198    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#199    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#200    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#201    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570:43)
#202    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597:12)
#203    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#204    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:321:14)
#205    RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#206    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#207    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1731:7)
#208    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#209    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:19)
#210    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#211    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#212    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#213    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#214    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#218    _invoke (dart:ui/hooks.dart:151:10)
#219    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#220    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
```

<img width="332" alt="Screen Shot 2022-04-29 at 0 32 14" src="https://user-images.githubusercontent.com/5731057/165849313-dd28d72d-582c-48be-9815-05288e306f91.png">

**Comment by jja08111** [comment]
Hi @ShaggyGettu, thanks for filling the issue.

Can you provide the `flutter docter -v`? I can't reproduce this issue.

**Comment by ShaggyGettu** [comment]
```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-IL)
    • Flutter version 2.10.5 at /Users/shaygettu/development/flutter_sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (11 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/shaygettu/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-11.0.15.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.66.2)
    • VS Code at /Users/shaygettu/development/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • iPhone 13 Pro Max (mobile) • FA97B36E-9BC4-4539-B6E8-33A21C0A8DF7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 101.0.4951.41

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by jja08111** [comment]
I've uploaded the `0.3.4` version to the pub.dev. thanks.
